### PR TITLE
Added OnTineInvoice

### PR DESCRIPTION
**Pull request by thenitai**

### CODE REVIEW

**Comment by thenitai** [comment]
Oh I see. You mentioned the cg package :+1: Cool.

**Comment by thenitai** [comment]
Comment on this:

As CheddarGetter allows multiple charges to be passed it needs to be in a structure. In node.js you would pass it like:

```
var _charge = {};
_charge.mine = {};
_charge.mine.chargeCode = (String);
_charge.mine.quantity =  (String);
_charge.mine.eachAmount = (String);
_charge.mine.description =  (String);
```

Thanks.

**Comment by thenitai** [comment]
@jamiter Are you going to add this? Would be great so I could pull your code from NPM :)

**Comment by jamiter** [comment]
Sorry, I missed this PR. I would like to merge it, but it's missing the option to pass in a `remoteAddress`, like defined here: http://docs.cheddargetter.com/#create-a-one-time-invoice

If you change `charges` into `data` then anything could be passed. You will have to pass in `{charges: charges}` yourself then. But you could also pass `{charges: charges, remoteAddress: remoteAddress}`.

**Comment by jamiter** [comment]
Ow, and please update the documentation in the readme to show that it now has this function :)

**Comment by thenitai** [comment]
Ok, updated it. As outlined above charges needs to be a structure you can pass this now together with remoteAddress. Here is an example:

```
// Create charges
var _data = {};
var _charge = {};
_charge.mine = {};
_charge.mine.chargeCode = invoice.chargecode;
_charge.mine.quantity = invoice.quantity.toString();
_charge.mine.eachAmount = invoice.eachamount.toString();
_charge.mine.description = invoice.description;
_data.charges = _charge;
_data.remoteAddress = '(some IP)';
```

Let me know when you merge it, so I can pull our lib in for my projects. Thank you.

**Comment by jamiter** [comment]
I messed up a bit but it is now merged and pushed to npm! 0.3.8 is now available.

**Comment by thenitai** [comment]
Great. So "CG" is in short just a one-to-one replacement for the old library, i.e. all methods and arguments stay the same, plus of course the new ones?

**Comment by jamiter** [comment]
Almost. The methods and arguments are indeed the same but what is returned is slightly different because of the way that the xml is parsed. It used to return things like transactions.transaction, but now it will simply be transactions (an array). So double check the return values, but they should be a lot better.

It also fixes an issue where you couldn't ser vatExempt.

Enjoy! :)

**Pull request closed without merging**
